# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Install dependencies for Selenium
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       chromium chromium-driver \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir .

# Expose no ports (stdio server)

# Default command to run the MCP server
CMD ["python", "-m", "web_analyzer_mcp.server"]
